version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:14.19-browsers

    working_directory: ~/react-chart-editor

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run: npm run test:percy
